version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:5.0.18
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    ports:
      - "${MONGO_EXT_PORT}:27017"

  backend:
    container_name: nodesv-luna-brew-house
    restart: always
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
