version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:5.0.18
    restart: always
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodata:/data/db
    ports:
      - "${MONGO_EXT_PORT}:27017"

  backend:
    container_name: nodesv-luna-brew-house
    restart: always
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo

  nextjs:
    container_name: frontend-nextjs
    build: ./fe
    restart: always
    env_file:
      - ./fe/.env
    ports:
      - "3008:3000" # Exponer el puerto 3007 al host
    environment:
      - NODE_ENV=production
      # Importante para que Next.js escuche en todas las interfaces
      - HOSTNAME=0.0.0.0
