version: "3.8"

services:
  backend:
    container_name: nodesv-luna-brew-house
    restart: always
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "3009:3001"
    links:
      - mongo
    depends_on:
      - mongo

  nextjs:
    container_name: frontend-nextjs
    build: ./fe
    restart: always
    env_file:
      - ./fe/.env
    ports:
      - "3008:3000" # Exponer el puerto 3008 al host
    environment:
      - NODE_ENV=production
      # Importante para que Next.js escuche en todas las interfaces
      - HOSTNAME=0.0.0.0
